services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ghcr.io/herzogelias/conduit-backend
    env_file:
    - ./backend/generated.env
    ports:
      - "8000:8000"
    volumes:
      - backend-code:/app
      - static-data:/var/www/static/
    restart: always
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ghcr.io/herzogelias/conduit-frontend
    ports:
      - "8282:80"
    volumes:
      - frontend-code:/app
    restart: always

volumes:
  frontend-code:
  backend-code:
  static-data:
  