name: ci

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout inkl. Submodules
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # 2️⃣ Generate env
      - name: Generate env
        run: |
          echo "DJANGO_SUPERUSER_PASSWORD=${{ secrets.DJANGO_PW }}" > generated.env 
          echo "DJANGO_SUPERUSER_EMAIL=${{ secrets.DJANGO_EMAIL }}" >> generated.env  
          echo "DJANGO_SUPERUSER_USERNAME=${{ secrets.DJANGO_USER }}" >> generated.env  
          echo "ALLOWED_HOSTS=${{ secrets.SERVER_IP }}" >> generated.env  
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> generated.env  

      # 3️⃣ Erstelle remote Ordnerstruktur
      - name: Create remote folders
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            mkdir -p /tmp/conduit/backend


      # 4️⃣ Kopiere docker-compose.yaml ins tmp/conduit
      - name: Copy docker-compose.yaml to server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "./docker-compose.yaml"
          target: "/tmp/conduit"

      # 5️⃣ Kopiere generated.env ins backend
      - name: Copy generated.env to backend folder
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "./generated.env"
          target: "/tmp/conduit/backend"

      # 6️⃣ Deploy via SSH: Login, Build & Up
      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin <<< ${{ secrets.GITHUB_TOKEN }}
            cd /tmp/conduit
            docker compose -f docker-compose.yaml down
            docker compose -f docker-compose.yaml --env-file backend/generated.env up -d --build
